### ISSUE TITLE
Please support custom regexp pattern to match className

### ISSUE THREAD

**Issue by Innei** [hyoban/tailwindcss-classname-highlight#2]
Generally in business, there are many variables for className, and these are not enough to cover them all.

It might be better if you can use the className atom matching rules of the tailwindcss server.

If not, it is recommended to open up custom regular matching.

Thank you.

Ref: https://github.com/hyoban/tailwindcss-classname-highlight/blob/main/src/utils.ts#L6

**Comment by hyoban** [comment]
Just find tailwindcss's defaultExtractor, this setting item should not be needed anymore.
