### ISSUE TITLE
unexpected underline outside jsx

### ISSUE THREAD

**Issue by LoTwT** [hyoban/tailwindcss-classname-highlight#27]
## description

unexpected underline outside jsx

<img width="926" alt="image" src="https://github.com/hyoban/tailwindcss-classname-highlight/assets/50254496/909e5e5d-9cb5-44af-a2ae-757b2eabad18">

## reproduction steps

- enable the extension
- pnpm create vite -> react-ts template
- pnpm add tailwindcss postcss autoprefixer -D
- npx tailwindcss init -p
- 
  ```js
  // tailwind.config.js
  /** @type {import('tailwindcss').Config} */
  export default {
    content: [
      './index.html',
      './src/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
      extend: {},
    },
    plugins: [],
  }
  ```
-
  ```jsx
  const [isLoading] = useState(false)

  useEffect(() => {
    document.documentElement.style.overflow = isLoading ? 'hidden' : 'auto'

    return () => {
      document.documentElement.style.overflow = 'auto'
    }
  }, [isLoading])
  ```

After disabling the extension, the underline will disapper.

### Reproduction

see above

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 123.30 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/Library/Caches/fnm_multishells/58748_1715304072290/bin/node
    npm: 10.5.2 - ~/Library/Caches/fnm_multishells/58748_1715304072290/bin/npm
    pnpm: 9.1.0 - ~/Library/Caches/fnm_multishells/58748_1715304072290/bin/pnpm
    bun: 1.1.7 - ~/.bun/bin/bun
  Browsers:
    Chrome: 124.0.6367.119
    Safari: 17.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hyoban** [comment]
This is expected behavior, please check the readme.

https://github.com/hyoban/tailwindcss-classname-highlight?tab=readme-ov-file#i-see-highlighting-but-some-classes-should-not-be-highlighted

I think it brings more convenience than inconvenience. So I won't change it.

**Comment by LoTwT** [comment]
♥️ Thank you for your explanation. TIL.

But I'd like to know more about your thoughts about whether this behavior will be user-decided despite its tailwind's default behavior and UnoCSS's strategy. Just for me, I seldom use tailwind utilities programmatically outside jsx / template.

**Comment by hyoban** [comment]
I can give you tons of examples of using tailwind utilities outside of `jsx/template`

1. As pointed out in the [tailwind documentation](https://tailwindcss.com/docs/content-configuration#class-detection-in-depth), this is useful for applying dynamic styles under known conditions.
1. Libraries such as [cva](https://cva.style/docs) or [twc](https://react-twc.vercel.app) need to define tailwind utilities outside `jsx/template`

If you don't have such a scenario, I'm also willing to accept a PR to add a configuration to turn off highlighting outside of `jsx/template`

**Comment by LoTwT** [comment]
Thank you.

**Comment by xxxxue** [comment]
在 X 上刷到的,  
跑来试用一下,刚装上还没10秒钟. 就发现了这个问题.
是否可以加一个开关,  只高亮 className 中的 关键字
现在其他地方写相同的关键字都会高亮 (不止图上的 inline)

![image](https://github.com/hyoban/tailwindcss-classname-highlight/assets/32764266/f9b2074d-f8e2-4c81-af4b-ef50aedffef8)

**Comment by hyoban** [comment]
@xxxxue 这个我已经解释了，你可以看前面的交流。我个人觉得显示是优大于劣的，如果你要加开关的话我也支持，但我自己不太有动力做。
