### ISSUE TITLE
Add helper comments for extended-colors when previewing.

### ISSUE THREAD

**Issue by LoTwT** [hyoban/tailwindcss-classname-highlight#28]
## description

I extend a color in the `tailwind.config.js` and use it in my project. When previewing, it displays the color in RGB, the tailwindcss generated results. When developing, I want to check the color to match the figma which produces the HEX instead of RGB.

```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "my-color": "#0070E0"
      }
    },
  },
  plugins: [],
}
```
![image](https://github.com/hyoban/tailwindcss-classname-highlight/assets/50254496/46f914cc-b55e-43b7-8101-2038e297374c)

## suggestion

![image](https://github.com/hyoban/tailwindcss-classname-highlight/assets/50254496/f00927ac-5ad9-427f-bd1d-0d8ab56f0207)

Could it add some helper comments like above?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
At present, this extension only detects valid classname. Hover to show the generated css is provided by the official tailwind extension itself. I'm not sure if we can modify its content.

**Comment by hyoban** [comment]
Although very basic, we now support hover and RGB to hex comments. Feel free to let me know if you have any more suggestions.
