### ISSUE TITLE
Wrong decorate

### ISSUE THREAD

**Issue by Innei** [hyoban/tailwindcss-classname-highlight#3]
Like this, this string or object field is not the css atom.

<img width="696" alt="image" src="https://github.com/hyoban/tailwindcss-classname-highlight/assets/41265413/54e80c40-1103-480d-9696-d8d328a06561">

**Comment by hyoban** [comment]
https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

This may be a feature because it is consistent with how tailwind works, like we can write

```ts
const colorVariants = {
  blue: 'bg-blue-600 hover:bg-blue-500',
  red: 'bg-red-600 hover:bg-red-500',
}
```

**Comment by hyoban** [comment]
Updated same logic with unocss
