### ISSUE TITLE
Causing "Aborted onWillSaveTextDocument-event after 1750ms" on under-powered laptops

### ISSUE THREAD

**Issue by Runc2333** [hyoban/tailwindcss-classname-highlight#30]
### Describe the bug

I noticed a significant increase in formatting time (using the default formatter) on my work laptop with an R5-5600H after enabling this plugin. Specifically, the Output -> Window panel shows "Aborted onWillSaveTextDocument-event after 1750ms." Disabling the plugin resolves the issue.

Interestingly, I couldn't reproduce this problem on my main workstation with a 13700KF, so there might need some more investigation. I’m not sure why classname highlighting would affect onWillSaveTextDocument, but it appears to be happening in this case.

Please let me know if you need any additional information for further investigation. I really appreciate the effort you’ve put into developing this plugin.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 87.78 GB / 127.81 GB
  Binaries:
    Node: 18.20.3 - ~\AppData\Roaming\nodejs\node.EXE  
    Yarn: 1.22.22 - ~\AppData\Roaming\nodejs\yarn.CMD  
    npm: 10.7.0 - ~\AppData\Roaming\nodejs\npm.CMD     
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hyoban** [comment]
Yes, I also encountered a similar problem. I will try to check it this week.

**Comment by Runc2333** [comment]
> Yes, I also encountered a similar problem. I will try to check it this week.

Identified this issue in `src\decoration-v3.ts` 's `extract` function.

![image](https://github.com/user-attachments/assets/87f432e9-5c8c-410c-8b01-beed66b90a13)

This function traverses the `generatedRule` array too many times. In my case it would be like 10 million times. Change the `generatedRule` from array to map solves the problem.

It might also be beneficial to changing `includedTextWithRange` to an interval-tree to increase the performance further.

Not sure if I should open a PR for this, since it seems like you alreary refactored this part and `onDidChangeTextDocument` is not implemented yet.

**Comment by hyoban** [comment]
feel free to open a PR, thank you so much.
