### ISSUE TITLE
not work in .jsx files

### ISSUE THREAD

**Issue by mancuoj** [hyoban/tailwindcss-classname-highlight#4]
![image](https://github.com/hyoban/tailwindcss-classname-highlight/assets/45707684/44314fca-92fb-419b-a85c-c30dfee194dd)

![image](https://github.com/hyoban/tailwindcss-classname-highlight/assets/45707684/c4d0ddc2-430c-4ad6-937f-0cf7720ef5f2)

**Comment by hyoban** [comment]
![ScreenShot 2024-02-17 17 26 53](https://github.com/hyoban/tailwindcss-classname-highlight/assets/38493346/33e691f5-f306-493b-bbcb-709b41112a10)

Works for me.

Please ensure that tailwind is installed correctly and the tailwind configuration file is included in the project. Reload the plugin after first tailwind installation.

And only file included in content will be highlighted.

**Comment by mancuoj** [comment]
Thanks, it works.
